import random


def gen_materias():
    data = ["Álgebra",
            "Cálculo Diferencial e Integral",
            "Computadoras y Programación",
            "Geometría Analítica",
            "Introducción a la Ingeniería en Computación",
            "Álgebra Lineal",
            "Cálculo Vectorial",
            "Comunicación",
            "Emprendimiento 1",
            "Programación Orientada a Objetos",
            "Taller de creatividad e innovación",
            "Ecuaciones Diferenciales",
            "Electricidad y Magnetismo (L)",
            "Emprendimiento 2",
            "Estructura de Datos",
            "Métodos Numéricos",
            "Bases de Datos 1",
            "Dispositivos Electrónicos (L)",
            "Emprendimiento 3",
            "Matemáticas Discretas",
            "Probabilidad y Estadística",
            "Administración de Proyectos",
            "Diseño Lógico (L)",
            "Diseño y Análisis de Algoritmos",
            "Lenguajes Formales y Autómatas",
            "Programación Web 1",
            "Compiladores",
            "Diseño de Sistemas Digitales (L)",
            "Ingeniería de Software",
            "Sistemas Operativos",
            "Microprocesadores y Microcontroladores (L)",
            "Programación Web 2",
            "Redes de computadoras 1 (L)",
            "Sistemas de Información",
            "Bases de Datos 2",
            "Habilidades Directivas",
            "Programación Móvil 1",
            "Redes de Computadoras 2",
            "Inteligencia Artificial",
            "Minería de Datos",
            "Seguridad Informática",
            "Graficación por Computadora",
            "Movilidad 1",
            "Temas Especiales de Computación 1",
            "Adquisición de Datos",
            "Instrumentación y Control",
            "Modelado y Simulación",
            "Movilidad 2",
            "Programación de Videojuegos 1",
            "Temas Especiales de Computación 2",
            "Administración de Sistemas Multiusuario",
            "Movilidad 3",
            "Movilidad 4",
            "Procesamiento Digital de Imágenes",
            "Procesamiento Digital de Señales",
            "Programación de Videojuegos 2",
            "Proyecto Escuela Industria",
            "Robótica",
            "Temas Especiales de Computación 3",
            "Temas Especiales de Computación 4",
            "Temas Especiales de Programación 1",
            "Análisis de Macrodatos",
            "Aprendizaje Automático",
            "Bioingeniería",
            "Cómputo Distribuido y Paralelo",
            "Cómputo en la Nube",
            "Internet de las Cosas",
            "Movilidad 5",
            "Movilidad 6",
            "Programación Móvil 2",
            "Reconocimiento de Patrones",
            "Seminario de Ingeniería en Computación",
            "Sistemas Expertos",
            "Temas Especiales de Seguridad Informática",
            "Temas Especiales de Bases de Datos",
            "Temas Especiales de Computación 5",
            "Temas Especiales de Computación 6",
            "Temas Especiales de Hardware",
            "Temas Especiales de Programación 2",
            "Temas Especiales de Redes",
            "Vinculación empresarial",
            "Visualización"]

    materias = random.sample(data, 5)

    return materias
